

export interface Champion { 
    name: String,
    cost: Number,
    traits: String[]
}

export const champions:Champion[] =  [
    {name:'Xayah',cost:4,traits:['Executionner','Elderwood','Keeper']},
    {name:'Rakan',cost:2,traits:['Elderwood','Keeper']},
    {name:'Veigar',cost:3,traits:['Elderwood','Mage']},
    {name:'Lulu',cost:2,traits:['Elderwood','Mage']},
    {name:'Maokai',cost:1,traits:['Elderwood','Brawler']},
    {name:'Nunu',cost:3,traits:['Elderwood','Brawler']},
    {name:'Ornn',cost:5,traits:['Elderwood','Vanguard','Blacksmith']},
    {name:'Garen',cost:1,traits:['Vanguard','Warlord']},
    {name:'Nidalee',cost:1,traits:['Sharpshooter','Warlord']},
    {name:'Jarvan IV',cost:2,traits:['Keeper','Warlord']},
    {name:'Vi',cost:2,traits:['Brawler','Warlord']},
    {name:'Katarina',cost:3,traits:['Assassin','Fortune','Warlord']},
    {name:'Tryndamere',cost:4,traits:['Slayer','Duelist','Warlord']},
    {name:'Azir',cost:5,traits:['Keeper','Emperor','Warlord']},
    {name:'Diana',cost:1,traits:['Spirit','Assassin']},
    {name:'Teemo',cost:2,traits:['Spirit','Sharpshooter']},
    {name:'Kindred',cost:3,traits:['Spirit','Executionner']},
    {name:'Yuumi',cost:3,traits:['Spirit','Mystic']},
    {name:'Fiora',cost:1,traits:['Enlightened','Duelist']},
    {name:'Janna',cost:2,traits:['Enlightened','Mystic']},
    {name:'Irelia',cost:3,traits:['Enlightened','Adept','Divine']},
    {name:'Morgana',cost:4,traits:['Enlightened','Syphoner']},
    {name:'Talon',cost:4,traits:['Enlightened','Assassin']},
    {name:'Nasus',cost:1,traits:['Divine','Syphoner']},
    {name:'Jax',cost:2,traits:['Divine','Duelist']},
    {name:'Kayle',cost:4,traits:['Divine','Executionner']},
    {name:'Lee Sin',cost:5,traits:['Divine','Duelist']},
    {name:'Zed',cost:2,traits:['Ninja','Slayer']},
    {name:'Akali',cost:3,traits:['Ninja','Assassin']},
    {name:'Kennen',cost:3,traits:['Ninja','Keeper']},
    {name:'Shen',cost:4,traits:['Ninja','Mystic','Adept']},
    {name:'Elise',cost:1,traits:['Cultist','Keeper']},
    {name:'Twisted Fate',cost:1,traits:['Cultist','Mage']},
    {name:'Vladimir',cost:2,traits:['Cultist','Syphoner']},
    {name:'Pyke',cost:2,traits:['Cultist','Assassin','Slayer']},
    {name:'Kalista',cost:3,traits:['Cultist','Duelist']},
    {name:'Sivir',cost:3,traits:['Cultist','Sharpshooter']},
    {name:'Aatrox',cost:4,traits:['Cultist','Vanguard']},
    {name:'Zilean',cost:5,traits:['Cultist','Mystic']},
    {name:'Nautilus',cost:2,traits:['Fabled','Vanguard']},
    {name:'Neeko',cost:3,traits:['Fabled','Mystic']},
    {name:'Chogath',cost:4,traits:['Fabled','Brawler']},
    {name:'Tristana',cost:1,traits:['Dragonsoul','Sharpshooter']},
    {name:'Brand',cost:1,traits:['Dragonsoul','Mage']},
    {name:'Braum',cost:2,traits:['Dragonsoul','Vanguard']},
    {name:'Shyvana',cost:3,traits:['Dragonsoul','Brawler']},
    {name:'Olaf',cost:4,traits:['Dragonsoul','Slayer']},
    {name:'Swain',cost:5,traits:['Dragonsoul','Syphoner']},
    {name:'Aurelion Sol',cost:4,traits:['Dragonsoul','Mage']},
    {name:'Samira',cost:5,traits:['Daredevil','Sharpshooter','Slayer']},
    {name:'Yasuo',cost:1,traits:['Exile','Duelist']},
    {name:'Yone',cost:5,traits:['Exile','Adept']},
    {name:'Sett',cost:5,traits:['Boss','Brawler']},
    {name:'Tahm Kench',cost:1,traits:['Fortune','Brawler']},
    {name:'Annie',cost:2,traits:['Fortune','Mage']},
    {name:'Darius',cost:3,traits:['Fortune','Slayer']},
    {name:'Sejuani',cost:4,traits:['Fortune','Vanguard']},
    {name:'Wukong',cost:1,traits:['Divine','Vanguard']},

]